config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get 'home/card_jon' => 'home#card_load', as: :loaded

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    confirmations: 'admins/confirmations',
    unlocks: 'admins/unlocks'
  }

  devise_scope :user do
    get "login", to: "users/sessions#new"
    resources :profiles
  end

  devise_scope :admin do
    get "login_admin", to: "admins/sessions#new"
    delete 'admins/user/:id' => 'admins/registrations#destroy_user', :as => :admin_destroy_user
    get 'admins/user/:id' => 'admins/registrations#edit_user', :as => :admin_edit_user
    resources :users
  end

  resources :cards
  resources :levels
  resources :private_cards
  resources :public_cards
  resources :questions
  resources :quizzes

  post :home, to: "home#card_load", as: :card_load
  get "home/card_load" => "home#card_load"

  post 'quiz_grade' => "quizzes#quiz_grade", as: :quiz_grade

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

	#authenticate that user is an admin before touching any quiz actions(Devise helper)
	# before_action :authenticate_admin!

	#for showing all quizzes
	def index
		@quizzes = Quiz.all
	end

	#action for a new quiz for the view (quiz/new.html.erb)
	def new
		@quiz = Quiz.new
	end

	#creating a new quiz
	def create
		@quiz = Quiz.new
		#create the quiz
		@quiz = Quiz.create(quiz_params)
  	#redirections if quiz was saved or not along with flash messaging
  	if @quiz.save
    		flash[:notice] = "Quiz was created"
    		#redirect to the home index page
    		redirect_to root_path
  	else
  		flash[:alert] = "Something went wrong."
    		redirect_to root_path
  	end
  end

	#for showing the currently selected quiz
  	def show
      @quizSelect = Quiz.find(1)
      @questions = @quizSelect.questions
      @cards = Card.all.limit(@quizSelect.questions.count*3).shuffle

  	end

    def quiz_grade
      puts params.inspect
      puts "HELLOOOOOOOOOOOO SETH"

      # get user input
      # check user input vs real answer
      # if correct add 1 to correct var
      #intialize correct var to zero.
      amtCorrect = 0
      #else keep going 
      #change integers to floats for division
      amtCorrect = amtCorrect.to_f
      quizLength = quizLength.to_f
      #at the end correct var/quiz.length
      quizGrade = amtCorrect / quizLength
      #display final quiz grade with flash message
      # if above .8 update user profile to next level and add 100 cred points
      #if they dont pass do nothing take them back to index page flash message "failed"
      if quizGrade > 0.8
        #use Activerecord's increment method to update profile level by 1
        current_user.profile.increment(profile_update_level, by = 1)
        #update the credibilty points by 100
        current_user.profile.increment(profile_update_credibilty, by = 100)
        #flash message with quiz grade
        flash[:notice] = "Congrats, you passed the quiz! (#{quizGrade * 100}%"
        flash[:notice] = "Your level and credibility were updated."
        redirect_to root_path
      else
        flash[:alert] = "Sorry, you did not score above an 80%"
        redirect_to root_path
      end
    end 

	#editing an already created quiz
  	def edit
		@quiz = Quiz.find(params[:id])
  	end

  	#updating an already created quiz
  	# def update
  	# 	@quiz = Quiz.find(params[:id])
  	# 	if @quiz.update_attributes(quiz_params)
  	# 		flash[:notice] ="Quiz was updated"
  	# 		redirect_to root_path
  	# 	else
  	# 		flash[:alert] = "Something went wrong."
  	# 		redirect_to root_path
  	# 	end
  	# end

    def update
    @quiz = Quiz.find(params[:id])
    @quiz.update_attributes(private_card_params)
    @quiz = Quiz.all
    respond_to do |page|
      page.js
    end
    end 
    
    def destroy
    #assign @quiz to the current quiz
    @quiz = Quiz.find(params[:id])
    #if succesful display message
      if @quiz.destroy
        flash[:notice] = "Quiz was deleted"
        #redirect to quiz index
        redirect_to root_path
      else
        flash[:alert] = "Something went wrong."
        redirect_to root_path
      end
    end
	
	#strong params
	private 

	#require the params of quiz
	def quiz_params 
    # params.require(:quiz).permit(:level_id, :name)
  end
  #for updating profile level
  def profile_update_level
    params.require(:profile).permit(:level)
  end
  #for updating profile credibility
  def profile_update_credibilty
    params.require.permit(:profile).permit(:credibility)
  end
   
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_new_quiz.html.erb
<p>Create a new quiz</p>
	<%= form_for @quiz do |c| %>
	<%= c.label :Quiz_Name %>
	<%= c.text_field :name %>
	<%= c.label :Level %>
	<%= c.number_field :level_id %>
	<%= c.submit :Create %>
<% end %>

app/views/quizzes/_quiz_questions_edit.html.erb
		

		<% quiz.questions.each do |q| %>
		<%= content_tag :p, "Question: #{q.question}", class: "quiz-question"%>
		<%= content_tag :p, "Answer: #{q.answer}", class: "quiz-answer"%>
		<button class="edit-question">Edit Question</button>
		<% end %>

app/views/quizzes/_quizzes_admin_crud.html.erb
<!-- go through each quiz and print the name, level, and questions -->
<% @quizzes.each do |quiz| %>

	<%= content_tag :p, "Quiz Name: #{quiz.name}", class: "quiz-name"%>
	<%= content_tag :p, "Quiz Level: #{quiz.level.id}", class: "quiz-name"%>
<!-- here is where the questions of the quiz are printed by iterating through each question belonging to the respective quiz -->
	<% quiz.questions.each do |q| %>
		<%= content_tag :p, "Question: #{q.question}", class: "quiz-question"%>
		<%= content_tag :p, "Answer: #{q.answer}", class: "quiz-answer"%>
		<!-- edit or destroy a question within a quiz -->
			<%= form_for q, remote: true, html: {method: :patch}, html: {class: "edit-question-form"} do |q| %>
			<%= q.label :Question %>
			<%= q.text_field :question %>
			<%= q.label :Answer %>
			<%= q.text_field :answer %>
			<%= q.label :Quiz_ID %>
			<%= q.number_field :quiz_id %>
			<%= q.submit :Update %>
		<% end %>
		<button class="edit-question">Edit Question</button>
		<button><%= link_to "Delete Question", question_path(q), method: :delete, data: { confirm: "You sure?" }, class: "delete-element" %></button>
	<% end %>
	<!-- create a new question for this quiz -->
	<h2>Add a question to this quiz</h2>
	<%= form_for @question do |q| %>
		<%= q.label :Question %>
		<%= q.text_field :question %>
		<%= q.label :Answer %>
		<%= q.text_field :answer %>
		<%= q.hidden_field :quiz_id, :value => "#{quiz.id}" %>
		<%= q.submit :Create_Question %>
	<% end %>
	<!-- edit or destroy entire quizzes, does not delete questions -->
	<button><%= link_to "Edit Quiz", edit_quiz_path(quiz) %></button>
	<button><%= link_to "Delete Quiz", quiz_path(quiz), method: :delete, data: { confirm: "You sure?" }, class: "delete-element" %></button>
<%end %>

app/views/quizzes/create.js.erb
// $("#new-quiz").onClick.html("<%= j render('quizzes/new_quiz' %>");

app/views/quizzes/edit.html.erb
<h2>Edit this quiz</h2>
<%= form_for @quiz do |q| %>
	<%= q.label :Quiz_Name %>
	<%= q.text_field :name %>
	<%= q.label :Level %>
	<%= q.number_field :level_id %>
	<%= q.submit :Update %>
<% end %>

app/views/quizzes/show.html.erb
<%= form_tag(quiz_grade_path, method: "post") do %>

<% @questions.each do |question| %>

<br>
<br>
<br>

	<%= content_tag :h1, "Question:#{question.question}", class: ""%>
		<% text = "" %>
		<% flag = false %>


<!-- 4 questions all togeth  -->
<!-- random number is generate and = X -->
<!-- x = correct answer for the question -->
<% x = rand(0..2) %>
<% for i in (0..2) %>
<!-- for i is not X then it will generate random answers from cards -->

	<% if i == x %>
		<% text = question.answer%>

		<% flag = true %>

	<% else %>
		<% text = @cards.pop.answer%>
		<% flag = false %>

	<% end %>


<!-- this is adding the radio buttons to the tag -->

	<%= radio_button_tag(:Random_Answers, "answer") %>
	<label for="answer"><%= "answer:#{text}" %></label>
	<br>
	<br>
<% end %>

	<!-- should be radio button radio_button_tag -->

<br>
<br>
<% end %>
<% end %>

<br>
<br>

  <%= submit_tag("Submit Quiz") %>

app/views/quizzes/update.js.erb
$(".quizzes").html("<%= j render('quizzes/quizzes_admin_crud') %>");