config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get 'home/card_jon' => 'home#card_load', as: :loaded

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    confirmations: 'admins/confirmations',
    unlocks: 'admins/unlocks'
  }

  devise_scope :user do
    get "login", to: "users/sessions#new"
    resources :profiles
  end

  devise_scope :admin do
    get "login_admin", to: "admins/sessions#new"
    delete 'admins/user/:id' => 'admins/registrations#destroy_user', :as => :admin_destroy_user
    get 'admins/user/:id' => 'admins/registrations#edit_user', :as => :admin_edit_user
    resources :users
  end

  resources :cards
  resources :levels
  resources :private_cards
  resources :public_cards
  resources :questions
  resources :quizzes

  post :home, to: "home#card_load", as: :card_load
  get "home/card_load" => "home#card_load"

  post 'quiz_grade' => "quizzes#quiz_grade", as: :quiz_grade

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # respond_to :html, :json, :only => [:card_load]
  def index

  end

  def find_card(tag)
    @findPrivateCard = PrivateCard.where(tag: tag)
  end

  def card_load
    #this basically says respond with this variable and go to the root_path
    @cardDeck = Level.find(1).cards.shuffle
    gon.cards = @cardDeck
    puts ""
    puts ""
    puts ""
    puts ""
    puts "GON: #{gon.cards}"
    puts ""
    puts ""
    puts ""
    puts ""
    puts params[:cardLevel]
    Gon::Base.render_data


    
    # Level.find(params[:cardLevel]).cards.shuffle
    # @cards= Level.find(params[:cardLevel]).cards.shuffle
    # gon.richard = 100
    # @wobble = "hello"
    # puts gon.watch.cardDisplay
    # render json: gon.cardDisplay

    # @my_ajax_var = {some: 'info'}.to_json
    # redirect_to loaded_path
  end

end

app/helpers/home_helper.rb
module HomeHelper

end

app/views/home/_cards.html.erb
<% if user_signed_in? || admin_signed_in? %>
<% @cards.each do |card| %>

<%= content_tag :p, "Question:#{card.question}?", class: "question"%>

<% if admin_signed_in? %>
<%= link_to "Delete Card", admin_destroy_user_path(card), method: :delete, data: { confirm: "You sure?" }, class: "delete-element" %>
<%end %>
<%= content_tag :p, "Answer: #{card.answer}", class: "answer" %>
<button><%= link_to "Next Card" class: "next-card", method: :put :remote :true %></button>
<% end %>
<% end %>

app/views/home/_cards_admin_crud.html.erb
<h2>All the cards</h2>
<% @cards.each do |card| %>
<!-- displays all the cards -->
<%= content_tag :p, "Level: #{card.level_id}", class: "level_id" %>
<%= content_tag :p, "Question:#{card.question}?", class: "question"%>
<%= content_tag :p, "Answer: #{card.answer}", class: "answer" %>

<!-- button and link to edit a card -->
<button><%= link_to "Edit Card", edit_card_path(card) %></button>
<button><%= link_to "Delete Card", card_path(card), method: :delete, data: { confirm: "You sure?" } %></button>
<% end %>

app/views/home/_profile_info.html.erb
<!-- profile display for the current user -->
<h1><%="Welcome #{current_user.profile.fname.upcase}" %></h1>	
<%= content_tag :p, "Username: #{current_user.profile.username} " %>
<%= content_tag :p, "Name: #{current_user.profile.fname} #{current_user.profile.lname}" %>
<%= content_tag :p, "Credibility Points: #{current_user.profile.credibility}" %>
<%= content_tag :p, "Level: #{current_user.profile.level}" %>
<div class="avatarPic">
	<%= image_tag current_user.profile.avatar.url(:medium) %>
</div>

app/views/home/_users.html.erb
<% if admin_signed_in? %>

<% @users.each do |user| %>

<%= content_tag :p, "User ID #{user.id}, Email: #{user.email}, Last signed in at #{user.last_sign_in_at}" %>
<button><%= link_to "Edit User", admin_edit_user_path(user) %></button>
<button><%= link_to "Delete User", admin_destroy_user_path(user), method: :delete, data: { confirm: "You sure?" }, class: "delete-element" %></button>

<% end %>
<% end %>

app/views/home/card_load.html.erb
<h1>TESTING</h1>

<%= params[:cardLevel] %>
<div class="testing">
</div>

app/views/home/card_load.js.erb
$(".card-container").html("<%= j render('cards/flip_card') %>");
console.log("gon");
console.log(gon.cards);
console.log("watched");
console.log(gon.watchedVariables);

app/views/home/index.html.erb
<!-- if user admin is logged in display admin's page -->
<% if admin_signed_in? %>
<h1>Admin's Home</h1>
<% end %>

<!-- if user is signed in display users page -->
<% if user_signed_in? %>
	<%= content_tag :div, id:"profile_content" do %>
	<%= render 'profile_info' %>
	<%end%>
<% end %>


<!-- Log in button hidden if user signed in -->
<% unless user_signed_in? || admin_signed_in? %>
<div class="landingTitle">
	<h1><br><br><br>Welcome to NYCDA Flash Card App!</h1>
</div>
<div class="userLogIn">
	<a href="login">User Log In</a>
</div>
<% end %>

<!-- Log in button hidden if admin is signed in -->
<% unless admin_signed_in? || user_signed_in?  %>
<div class="adminLogIn">
	<a href="login_admin">Admin Log In</a>
</div>
<% end %>

<!-- below here visible to both user and admin -->
<!-- some partials may have logic within tdhem that prevents -->
<!-- a user or admin from seeing certain content contained within the partial -->
	<% if admin_signed_in? %>

			<li>
	  		<!-- show the logout button if anyone is logged in -->
	  		<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>     
	  		</li>
	 <% end %>
			<% if user_signed_in? %> 
				<nav>	
					<ul> 
			  			<li>
			  				<button class ="create-private-cards">Create Private Card</button>
			  			</li>
			  			<li>
			  				<button class="show-private-cards-button">Private Cards</button>
			  			</li>
			  			<li>
			  				<button class="show-public-cards-button">Public Cards</button>
			  			</li>
			  			<li>
			  				<button id="editp">Profile</button>
			  			</li>
			  			<li>
			  			<!-- show the logout button if anyone is logged in -->
			  			<%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 
			  			</li>
					</ul>
				</nav>

  	<!-- public card CRUD actions -->
  	<%= content_tag :div, class: "publicCard" do %>
	<%= render "public_cards/public_card_crud", cards: @cards %>
	<% end %>
	<!-- create a public card -->
	<%= content_tag :div, class: "publicCard" do %>
	<%= render "public_cards/create_public_card", cards: @cards %>
	<% end %>
	<!-- all the cards. No CRUD actions -->
	<%= content_tag :div, class: "cards" do %>
	<%= render "cards/cards", cards: @cards %>
	<% end %>

	<!-- private cards only need to be shown to a user -->
	<% if user_signed_in? %>
			<!-- user's private cards. Not visible to admins -->
		<%= content_tag :div, class: "privateCard" do %>
		<%= render "private_cards/private_cards", privateCard: @privateCard %>
		<% end %>
		<!-- <button value="2">Display Card</button> -->
		<%= content_tag :div, class: "privateCardSingle" do %>
		<%= render "private_cards/private_cards_info", selectedCard: PrivateCard.find(1) %>
		<% end %>

		<%= content_tag :div, class: "privateCardEdit" do %>
		<%= render "private_cards/private_card_edit", card: PrivateCard.find(1) %>
		<% end %>
	<% end %>
<br>	
<br>	
<br>	
<br>	
<% end %>

<!-- below here is only visible to admins -->
<% if admin_signed_in? %>
	<!-- all the users -->
	<button class="show-all-users">Display All Users</button>
	<%= content_tag :div, class: "users" do %>
	<%= render "users/users", users: @users %>
	<% end %>
	<!-- all the cards -->
	<button class="show-cards-button">Display All Cards</button>
	<%= content_tag :div, class: "cards" do %>
	<%= render "cards/cards_admin_crud", cards: @cards %>
	<% end %>
	<!-- create a new card -->
	<button class="create-new-card-button">Create A New Card</button>
	<%= content_tag :div, class: "new-card" do %>
	<%= render "cards/new_card_admin", card: @card %>
	<% end %>
	<!-- all quiz RUD actions, including quiz questions. Create is seperate-->
	<button class="show-quizzes-button">Display All Quizzes</button>
	<%= content_tag :div, class: "quizzes" do %>
	<%= render "quizzes/quizzes_admin_crud", quiz: @quiz %>
	<% end %>

	<!-- for toggling form for creating a new quiz -->
	<button id="new-quiz-button">Create Quiz</button>
	<!-- the rendered view for creating a quiz -->
	<%= content_tag :div, class: "create-quiz" do %>
	<%= render "quizzes/new_quiz", quiz: @quiz %>
	<% end %>
<% end %>
	
<!-- only show if user is signed in -->
<% if user_signed_in? %>
	<%= content_tag :div, class: "profiles" do %>
	<%= render "profiles/edit_profile", profile: @profile %>
	<% end %>
<% end %>

<!-- FLIP CARD -->
<%= content_tag :div, class: "flipCard" do %>
<%= render "cards/flip_card" %>
<% end %>

app/views/home/index.js.erb
$(".flipCard").html("<%= j render('cards/flip_card', cards: gon.cards) %>");