config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get 'home/card_jon' => 'home#card_load', as: :loaded

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    confirmations: 'admins/confirmations',
    unlocks: 'admins/unlocks'
  }

  devise_scope :user do
    get "login", to: "users/sessions#new"
    resources :profiles
  end

  devise_scope :admin do
    get "login_admin", to: "admins/sessions#new"
    delete 'admins/user/:id' => 'admins/registrations#destroy_user', :as => :admin_destroy_user
    get 'admins/user/:id' => 'admins/registrations#edit_user', :as => :admin_edit_user
    resources :users
  end

  resources :cards
  resources :levels
  resources :private_cards
  resources :public_cards
  resources :questions
  resources :quizzes

  post :home, to: "home#card_load", as: :card_load
  get "home/card_load" => "home#card_load"

  post 'quiz_grade' => "quizzes#quiz_grade", as: :quiz_grade

end

app/models/public_card.rb
class PublicCard < ActiveRecord::Base
	belongs_to :user
end

app/controllers/public_cards_controller.rb
class PublicCardsController < ApplicationController

  #creating a new public card
  def create
    @publicCard = PublicCard.new
    #create the card
    @publicCard = PublicCard.create(public_card_params)
    #update the newly created card with the current user who created it
    PublicCard.last.update(user_id: current_user.id)
    #redirections if card was saved or not along with flash messaging
    if @publicCard.save
      flash[:notice] = "Public card was created"
      #redirect to the cards index page
      redirect_to root_path
    else
      flash[:alert] = "Something went wrong."
      redirect_to root_path
    end
  end

  #for showing the currently selected card
  def show
    @publicCard = PublicCard.find(params[:id])
  end

  #action for view for editing an already created card
  def edit
    #set @publicCard to the current card, which was linked from the cards index view
    @publicCard = PublicCard.find(params[:id])
    
  end

  #action for updating a card
  def update
    @publicCard = PublicCard.find(params[:id])
   #update the card with the submitted params
    if @publicCard.update(public_card_params)
    #if succesful display message
      flash[:notice] = "Public card was updated"
      #redirect to the that card's page
      redirect_to root_path
    else
      #if something went wrong, redirect to that card's page
      flash[:alert] = "Something went wrong."
      redirect_to root_path
    end
  end

  #action for destroying a card
  def destroy
    #assign @card to the current card
    @publicCard = PublicCard.find(params[:id])
    #if succesful display message
    if @publicCard.destroy
      flash[:notice] = "Card was destroyed"
      #redirect to cards index
      redirect_to root_path
    else
      flash[:alert] = "Something went wrong."
      redirect_to root_path
    end
  end

  
  #strong params
  private 

  #require the params of card and permit both question and answer to be written in DB
  def public_card_params 
    params.require(:public_card).permit(:question, :answer, :user_id, :tag)
  end
end

app/helpers/public_cards_helper.rb
module PublicCardsHelper
end

app/views/public_cards/_create_public_card.html.erb
<br><h2>Create a new public card</h2>
<p>This card will be visible to everyone!</p>

<!-- for for creating a new public card -->
<%= form_for @publicCard do |c| %>
	<%= c.label :Question %>
	<%= c.text_field :question %><br>
	<%= c.label :Answer %>
	<%= c.text_field :answer %><br>
	<%= c.label :Tag %>
	<%= c.select :tag, [['HTML','HTML'],['CSS','CSS'],['JS','JS'],['RUBY','RUBY'],['RAILS', 'RAILS'],['OTHER','OTHER']] %><br>
	<%= c.submit :Create %><br>
<% end %>

app/views/public_cards/_public_card_crud.html.erb
<h2>All the public cards</h2><br>
<% @publicCards.each do |card| %><br><br><br><br><br><br>
	<!-- displays all the cards -->
	<%= content_tag :p, "Question:#{card.question}?", class: "question"%>
	<%= content_tag :p, "Answer: #{card.answer}", class: "answer" %>
	<%= content_tag :p, "Tag: #{card.tag}", class: "tag" %><br>
	<%= content_tag :p, "Created By: #{card.user.email}", class: "user-email" %>
	<!-- button and link to edit a card -->
	<% if current_user == card.user_id || current_admin %>
	<!-- only display edit button if the public card was created by the current user or is an admin -->
	<button><%= link_to "Edit Card", edit_public_card_path(card) %></button>
	<!-- only display delete button if the public card was created by the current user or is an admin -->
	<button><%= link_to "Delete Card", public_card_path(card), method: :delete, data: { confirm: "You sure?" } %></button>
	<% end %>
<% end %>

app/views/public_cards/edit.html.erb
<h1>PublicCards#edit</h1>
<p>Find me in app/views/public_cards/edit.html.erb</p>