config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get 'home/card_jon' => 'home#card_load', as: :loaded

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    confirmations: 'admins/confirmations',
    unlocks: 'admins/unlocks'
  }

  devise_scope :user do
    get "login", to: "users/sessions#new"
    resources :profiles
  end

  devise_scope :admin do
    get "login_admin", to: "admins/sessions#new"
    delete 'admins/user/:id' => 'admins/registrations#destroy_user', :as => :admin_destroy_user
    get 'admins/user/:id' => 'admins/registrations#edit_user', :as => :admin_edit_user
    resources :users
  end

  resources :cards
  resources :levels
  resources :private_cards
  resources :public_cards
  resources :questions
  resources :quizzes

  post :home, to: "home#card_load", as: :card_load
  get "home/card_load" => "home#card_load"

  post 'quiz_grade' => "quizzes#quiz_grade", as: :quiz_grade

end

app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :level

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  #authenticate that user is an admin before touching any card actions(Devise helper)
  before_action :authenticate_admin!

  #creating a new card
  def create
    @card = Card.new
    #create the card
    @card = Card.create(card_params)
    #redirections if card was saved or not along with flash messaging
    if @card.save
      flash[:notice] = "Card was created"
      #redirect to the cards index page
      redirect_to root_path
    else
      flash[:alert] = "Something went wrong."
      redirect_to root_path
    end
  end

  #for showing the currently selected card
  def show
    @card = Card.find(card_params[:id])
  end

  #action for view for editing an already created card
  def edit
    #set @card to the current card, which was linked from the cards index view
    @card = Card.find(params[:id])
    
  end

  #action for updating a card
  def update
    @card = Card.find(params[:id])
   #update the card with the submitted params
    if @card.update(card_params)
    #if succesful display message
      flash[:notice] = "Card was updated"
      #redirect to the that card's page
      redirect_to root_path
    else
      #if something went wrong, redirect to that card's page
      flash[:alert] = "Something went wrong."
      redirect_to root_path
    end
  end

  #action for destroying a card
  def destroy
    #assign @card to the current card
    @card = Card.find(params[:id])
    #if succesful display message
    if @card.destroy
      flash[:notice] = "Card was destroyed"
      #redirect to cards index
      redirect_to root_path
    else
      flash[:alert] = "Something went wrong."
      redirect_to root_path
    end
  end

  
  #strong params
  private 

  #require the params of card and permit both question and answer to be written in DB
  def card_params 
    params.require(:card).permit(:question, :answer, :level_id)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_cards.html.erb
<% if user_signed_in? || admin_signed_in? %>
<% @cards.each do |card| %>

<%= content_tag :p, "Question:#{card.question}?", class: "question"%>

<% if admin_signed_in? %>
<%= link_to "Delete Card", admin_destroy_user_path(card), method: :delete, data: { confirm: "You sure?" }, class: "delete-element" %>
<%end %>
<%= content_tag :p, "Answer: #{card.answer}", class: "answer" %>
<% end %>
<% end %>

app/views/cards/_flip_card.html.erb
<!-- believe this is necessary for gon to work with uJs -->
<%=  Gon::Base.render_data %>

<% if user_signed_in? %>
<!-- whole card -->
<div class="cardPlusButtons">
  <div class="card-container">
    <div id="card"> 
      <!-- front of card -->
      <div class="front"> 
       <div>
        <%= content_tag :p, "", class: "cardQuestion"%>
      </div>
    </div> 
    <!-- back of card -->
    <div class="back">
      <div>
        <%= content_tag :p, "", class: "cardAnswer" %>
      </div>
    </div> 
  </div>

  <!-- navigation buttons for cards -->
  <div class="nextPrevButtons">
    <button class="nextButton">Next</button>
    <button class="previousButton">Previous</button>
  </div>

  <div class="loadButton">
    <!-- form for selecting a new deck of cards from a level -->
    <%= form_tag(card_load_path, remote: :true, method: 'post') do %>  
    <%= label_tag("Select_Level") %>
    <%= select_tag(:cardLevel, options_for_select([['One', 1],['Two', 2],['Three', 3],['Four', 4],['Five', 5],['Six', 6],['Seven', 7],['Eight', 8],['Nine', 9],['Ten', 10],['Eleven', 11],['Twelve', 12]], selected: :option)) %>
    <br>
    <br>
    <%= submit_tag("Load") %>
    <% end %>  
  </div>
</div>
<br>
<br>
<button><%= link_to('Take a Quiz', quiz_path(@quizTake))  %></button>

<% end %>

app/views/cards/_new_card_admin.html.erb
<h2>Create a new card</h2>

<!-- for for creating a new card -->
<%= form_for @card do |c| %>
	<%= c.label :Question %>
	<%= c.text_field :question %>
	<%= c.label :Answer %>
	<%= c.text_field :answer %>
	<%= c.label :Level %>
	<%= c.number_field :level_id %>
	<%= c.submit :Create %>
<% end %>

app/views/cards/edit.html.erb
<h1>Cards#edit</h1>
<p>Find me in app/views/cards/edit.html.erb</p>

<h2>Edit this card</h2>
<%= form_for @card do |c| %>
	<%= c.label :Question %>
	<%= c.text_field :question %>
	<%= c.label :Answer %>
	<%= c.text_field :answer %>
	<%= c.label :Level %>
	<%= c.number_field :level_id %>
	<%= c.submit :Update %>
<% end %>